## Import packages

In [1]:
## import required packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
from statistics import *

## Import dataset

In [2]:
## import data from feature folder, I renamed the csv name 
data1 = pd.read_csv('/Users/a/Desktop/safety/features/part1.csv')
data2 = pd.read_csv('/Users/a/Desktop/safety/features/part2.csv')
data3 = pd.read_csv('/Users/a/Desktop/safety/features/part3.csv')
data4 = pd.read_csv('/Users/a/Desktop/safety/features/part4.csv')
data5 = pd.read_csv('/Users/a/Desktop/safety/features/part5.csv')
data6 = pd.read_csv('/Users/a/Desktop/safety/features/part6.csv')
data7 = pd.read_csv('/Users/a/Desktop/safety/features/part7.csv')
data8 = pd.read_csv('/Users/a/Desktop/safety/features/part8.csv')
data9 = pd.read_csv('/Users/a/Desktop/safety/features/part9.csv')
data10 = pd.read_csv('/Users/a/Desktop/safety/features/part10.csv')

df = pd.concat([data1,data2,data3,data4,data5,data6,data7,data8,data9,data10],axis=0) ##concatenate all data
df = df.sort_values(by=['bookingID','second'],ascending=True)  ## sort values first by booking_id then by seconds

In [3]:
df.describe()

,bookingID,Accuracy,Bearing,acceleration_x,acceleration_y,acceleration_z,gyro_x,gyro_y,gyro_z,second,Speed
count,1.613556e+07,1.613556e+07,1.613556e+07,1.613556e+07,1.613556e+07,1.613556e+07,1.613556e+07,1.613556e+07,1.613556e+07,1.613556e+07,1.613556e+07
mean,8.184819e+11,1.161035e+01,1.689684e+02,6.914529e-02,4.468976e+00,8.942974e-01,-1.710847e-03,2.800733e-04,-2.569688e-04,3.803484e+03,9.006543e+00
std,4.952476e+11,8.691672e+01,1.072966e+02,1.424161e+00,8.130664e+00,3.251549e+00,1.445619e-01,3.400630e-01,1.480824e-01,1.436686e+06,8.106415e+00
min,0.000000e+00,7.500000e-01,0.000000e+00,-7.841969e+01,-7.299412e+01,-7.844842e+01,-4.845575e+01,-7.488861e+01,-5.355445e+01,0.000000e+00,-2.000000e+00
25%,3.779571e+11,3.900000e+00,7.800000e+01,-5.081238e-01,-2.022476e+00,-9.316101e-01,-2.678888e-02,-2.993851e-02,-1.876500e-02,2.410000e+02,1.020000e+00
50%,8.074539e+11,4.250000e+00,1.688700e+02,6.137085e-02,9.081485e+00,7.757450e-01,-6.432411e-04,2.645046e-04,-3.542004e-05,5.200000e+02,7.530000e+00
75%,1.254130e+12,8.000000e+00,2.629840e+02,6.350620e-01,9.709778e+00,2.750938e+00,2.330639e-02,3.143085e-02,1.823425e-02,8.630000e+02,1.548000e+01
max,1.709397e+12,6.070101e+03,3.599995e+02,6.687346e+01,7.505589e+01,7.805576e+01,3.983975e+01,8.031496e+01,6.630078e+01,1.495797e+09,1.480186e+02

In [4]:
## clean the wrong second record
df=df.loc[df.second < 43200]  ## trip less than 12 hours 
df=df.loc[df.Speed > 0] # speed larger than 0 and less than 200km/h
df=df.loc[df.Speed < 55.56] # speed larger than 0 and less than 200km/h
df=df.loc[df.Accuracy < 50] ## ensure accuracy level

In [5]:
df.describe()

,bookingID,Accuracy,Bearing,acceleration_x,acceleration_y,acceleration_z,gyro_x,gyro_y,gyro_z,second,Speed
count,1.310108e+07,1.310108e+07,1.310108e+07,1.310108e+07,1.310108e+07,1.310108e+07,1.310108e+07,1.310108e+07,1.310108e+07,1.310108e+07,1.310108e+07
mean,8.177589e+11,6.960524e+00,1.795009e+02,6.217828e-02,3.770251e+00,7.739069e-01,-2.182377e-03,9.927901e-04,-2.125147e-04,6.185456e+02,1.109622e+01
std,4.951790e+11,5.054615e+00,1.015915e+02,1.447169e+00,8.512912e+00,3.283866e+00,1.439362e-01,3.360050e-01,1.423898e-01,4.574208e+02,7.580414e+00
min,0.000000e+00,7.500000e-01,0.000000e+00,-7.841969e+01,-7.299412e+01,-7.593699e+01,-3.347175e+01,-7.488861e+01,-3.746538e+01,0.000000e+00,7.569697e-27
25%,3.779571e+11,3.900000e+00,9.200000e+01,-5.602603e-01,-8.295816e+00,-1.098642e+00,-3.277731e-02,-3.728426e-02,-2.258857e-02,2.580000e+02,4.269649e+00
50%,7.988639e+11,5.000000e+00,1.790000e+02,5.148491e-02,8.916007e+00,6.673837e-01,-1.339628e-03,9.211848e-04,-9.155273e-05,5.450000e+02,1.045967e+01
75%,1.254130e+12,8.576000e+00,2.680000e+02,6.763620e-01,9.692338e+00,2.662352e+00,2.849992e-02,3.970624e-02,2.216123e-02,8.870000e+02,1.712764e+01
max,1.709397e+12,4.999300e+01,3.599995e+02,6.687346e+01,7.505589e+01,7.805576e+01,3.983975e+01,8.031496e+01,4.505986e+01,8.224000e+03,5.055000e+01

In [6]:
##groupby bookingid then generate a list for each field
df = df.groupby(['bookingID']).agg(lambda x: list(x))

In [18]:
## the csv file is renamed as label
label = pd.read_csv('/Users/a/Desktop/safety/labels/label.csv') 
## sort the dataframe so that for duplicate bookingid, the label associated with the last record is always 1(dangerous)
label = label.sort_values(by = ['bookingID','label'],ascending=True) 
## drop the duplicate values except the last occurance, if the bookingid has both label 0 and 1, we treat it as 1(dangerous) because it is suspicious
label = label.drop_duplicates(subset=['bookingID'],keep='last') 
## set bookingID to be the index
label = label.set_index('bookingID',drop = True)

In [20]:
##join features and labels
df_new = pd.concat([df,label],axis=1)

In [25]:
df_new = df_new.dropna(axis=0)
df_new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19971 entries, 0 to 1709396983975
Data columns (total 11 columns):
Accuracy          19971 non-null object
Bearing           19971 non-null object
acceleration_x    19971 non-null object
acceleration_y    19971 non-null object
acceleration_z    19971 non-null object
gyro_x            19971 non-null object
gyro_y            19971 non-null object
gyro_z            19971 non-null object
second            19971 non-null object
Speed             19971 non-null object
label             19971 non-null int64
dtypes: int64(1), object(10)
memory usage: 1.8+ MB

In [26]:
## export the merged dataframe for future use
import pickle
with open("/Users/a/Desktop/df_raw.pkl","wb") as handle:
    pickle.dump(df_new,handle,protocol=pickle.HIGHEST_PROTOCOL)